### ISSUE TITLE
Upcoming games feature

### ISSUE THREAD

**Issue by kraleppa** [szarbartosz/ekstraklasa-scraper#5]
Please create an endpoint that allows you to fetch upcoming games

IMO by default it should return only games in the next round, but user should also be able to pass `endDate` as query params to fetch later games also

This endpoint should also have the possibility to filter matches by a team name using `teamName` query param

**Comment by szarbartosz** [comment]
Resolving based on [this pr](https://github.com/szarbartosz/ekstraklasa-scraper/pull/6)
