### ISSUE TITLE
Incorrect last results

### ISSUE THREAD

**Issue by kraleppa** [szarbartosz/ekstraklasa-scraper#7]
Apparently scraper returns incorrect values for `lastResults` param - it misses the most recent game

JSON from scraper
<img width="989" alt="Screenshot 2024-08-05 at 12 52 56" src="https://github.com/user-attachments/assets/570af6d4-e2a3-48a0-bb66-2bffc1b260b9">

Actual Jaga results
<img width="670" alt="Screenshot 2024-08-05 at 12 54 34" src="https://github.com/user-attachments/assets/58da171d-71a9-4041-9efe-6eae15756d5f">

**Comment by kraleppa** [comment]
@szarbartosz is there a chance to resolve it?

**Comment by szarbartosz** [comment]
@kraleppa the root of the problem is the fact, that we are scraping the official ekstraklasa table: https://www.ekstraklasa.org/tabela/sezon - they update the last round results only after the last match of the round

**Comment by szarbartosz** [comment]
@kraleppa switched deployed version so that it scrapes latest `eurosport` table - please let me know the results are displayed as expected

**Comment by kraleppa** [comment]
It's working fine, but as far as I can see the results are in incorrect order - take a look at Zagłębie

From API
![Screenshot 2024-08-05 at 16 28 47](https://github.com/user-attachments/assets/e44e56f3-48c5-4ccc-b7a3-160f269d1ac8)

Google
<img width="636" alt="Screenshot 2024-08-05 at 16 28 59" src="https://github.com/user-attachments/assets/1abf3d66-cd80-4194-a2f7-00f22a9834f8">

As you can see first in the array are the oldest results

**Comment by szarbartosz** [comment]
it's displayed on eurosport website in this order, but I agree that it's unintuitive - will fix that
